import turtle as t
week = ['black','grey','darkgreen','gold','violet','purple','green','red']
t.setup(700,400,200,200)
t.penup()
t.fd(-250)
t.pendown()
t.pensize(25)
t.seth(-40)
for i in range(2):
    t.pencolor("black")
    t.circle(40,80)
    t.pencolor("darkgreen")
    t.circle(-40,80)
for i in range(2):
    t.pencolor("grey")
    t.circle(40,80)
    t.pencolor("blue")
    t.circle(-40,80)
t.pencolor("gold")
t.circle(40,80/2)
t.pencolor("violet")
t.fd(40)
t.pencolor("purple")
t.circle(16,180)
t.pencolor("red")
t.fd(40*2/3)
